name: "ensemble_test"
max_batch_size: 256
platform: "ensemble"
input[
 {
   name: 'in',
   data_type: TYPE_FP32,
   dims: [1]
 }
]
output [
 {
   name: 'out',
   data_type: TYPE_FP32,
   dims: [1]
 }
]

ensemble_scheduling {
  step [
    {
      model_name: "model1",
      model_version: 1,
      input_map {
        key: "in_model1",
        value: "in"
      },
      output_map {
        key: "out_model1",
        value: "intermediate_out"
      }
    },
    {
      model_name: "modeltorch",
      model_version: 1,
      input_map {
        key: "modeltorch_in",
        value: "intermediate_out"
      },
      output_map {
        key: "modeltorch_out",
        value: "torch_out"
      }
    },
    {
      model_name: "model2",
      model_version: 1,
      input_map {
        key: "in_model2",
        value: "torch_out"
      },
      output_map {
        key: "out_model2",
        value: "out"
      }
    }
  ]
}