max_batch_size: 1000
input[
 {
   name: 'peptide_sequences_1',
   data_type: TYPE_STRING,
   dims: [-1]
 }]
 input[
 {
   name: 'peptide_sequences_2',
   data_type: TYPE_STRING,
   dims: [-1]

 }
]
output [
 {
   name: 'peptides_in_1:0',
   data_type: TYPE_INT32,
   dims: [30]
 }]
 output [
 {
   name: 'peptides_in_2:0',
   data_type: TYPE_INT32,
   dims: [30]
 }
]
