max_batch_size: 7000
input [
  {
    name: 'precursor_charge_in_int:0',
    data_type: TYPE_INT32,
    dims: [1],
  }
]
output [
 {
   name: 'collision_energy_in:0',
   data_type: TYPE_FP32,
   dims: [1]
 }
]
