name: "fragment_mz"
backend: "python"
input[
 {
   name: 'ProForma',
   data_type: TYPE_STRING,
   dims: [-1]
 },
 {
   name: 'charges',
   data_type: TYPE_INT32,
   dims: [-1]
 },
 {
   name: 'ion_series',
   data_type: TYPE_STRING,
   dims: [-1]
 }
]
output [
 {
   name: 'output_fragmentmz',
   data_type: TYPE_FP64,
   dims: [-1,-1,-1,-1]
 }
]
