max_batch_size: 1000

input [
   {
   name: 'precursor_charges',
   data_type: TYPE_INT32,
   dims: [-1]
  }
]

output [
 {
   name: 'precursor_charges_FP',
   data_type: TYPE_FP32,
   dims: [1]
 }
]
