version: '3.8'

services:
  serving:
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             device_ids: ["${GPU_DEVICE}"]
             capabilities: [ gpu ]