max_batch_size: 10
input[
 {
   name: 'single_ac',
   data_type: TYPE_FP32,
   dims: [60,6]
 }
]
output [
 {
   name: 'diamino_ac',
   data_type: TYPE_FP32,
   dims: [30,6]
 }
]
instance_group [
    {
      count: 1
      kind: KIND_CPU
    }
]
