name: "Prosit_2019_intensity"
max_batch_size: 7000
platform: "tensorflow_savedmodel"

input [
	{
	  name: 'input_141',
	  data_type: TYPE_INT32,
	  dims: [60,6],
	},
	{
	  name: 'input_142',
	  data_type: TYPE_INT32,
	  dims: [30,6],
	},
	{
	  name: 'input_144',
	  data_type: TYPE_INT32,
	  dims: [60,20],
	}
]

output [
  {
   name: 'dense_323',
   data_type: TYPE_FP32,
   dims: [1]
  }
]
