name: "AlphaPept_Preprocess_mod"
max_batch_size: 7000
backend: "python"
input[
 {
   name: 'mods:0',
   data_type: TYPE_STRING,
   dims: [-1]
 },
 {
   name: 'mod_sites:0',
   data_type: TYPE_STRING,
   dims: [-1]
 },
 {
   name: 'nAA:0',
   data_type: TYPE_INT32,
   dims: [-1]
 }
]
output [
 {
   name: 'output:0',
   data_type: TYPE_INT32,
   dims: [-1,109]
 }
]
