FROM swaggerapi/swagger-ui as swagger-dlomix

RUN sed -i 's/SwaggerUIStandalonePreset/SwaggerUIStandalonePreset.slice(1)/' /usr/share/nginx/html/index.html
ENV SWAGGER_JSON=/workspace/swagger/swagger.yml