max_batch_size: 7000

input[
  {
   name: 'peptides_in:0',
   data_type: TYPE_STRING,
   dims: [-1]
  },
  {
   name: 'peaks_in:0',
   data_type: TYPE_FP32,
   dims: [-1,8]
  }
]
output [
 {
   name: 'intensities',
   data_type: TYPE_FP32,
   dims: [-1]
 },
 {
   name: 'mz',
   data_type: TYPE_FP32,
   dims: [-1]
 }
]
