name: "Prosit_2019_intensity"
max_batch_size: 7000
platform: "tensorflow_savedmodel"

input [
	{
	  name: 'collision_energy_in:0',
	  data_type: TYPE_FP32,
	  dims: [1],
	},
	{
	  name: 'peptides_in:0',
	  data_type: TYPE_INT32,
	  dims: [30],
	},
	{
	  name: 'precursor_charge_in:0',
	  data_type: TYPE_FP32,
	  dims: [6],
	}
]

output [
  {
   name: 'out/Reshape:0',
   data_type: TYPE_FP32,
   dims: [174]
  }
]
