max_batch_size: 1000
input[
 {
   name: 'stripped_peptide',
   data_type: TYPE_STRING,
   dims: [1]
 }
]
output [
 {
   name: 'ccs_feat',
   data_type: TYPE_FP32,
   dims: [4]
 }
]
instance_group [
    {
      count: 1
      kind: KIND_CPU
    }
]
