max_batch_size: 7000
platform: "ensemble"
input [
  {
   name: 'in/proforma',
   data_type: TYPE_STRING,
   dims: [-1]
  }
]
output [
  {
   name: 'out/irt',
   data_type: TYPE_FP32,
   dims: [1]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "Prosit_Preprocess_peptide"
      model_version: 1
      input_map {
        key: "peptides_in_str:0"
        value: "in/proforma"
      },
      output_map {
        key: "peptides_in:0"
        value: "out/sequence_int"
      }
    },
    {
      model_name: "Prosit_2020_irt_TMT_core"
      model_version: 1
      input_map {
        key: "peptides_in:0"
        value: "out/sequence_int"
      },
      output_map {
        key: "prediction/BiasAdd:0"
        value: "out/irt"
      }
    }
  ]
}
