max_batch_size: 5000
input[
 {
   name: 'peptide_sequences',
   data_type: TYPE_STRING,
   dims: [1]
 }
]
output [
 {
   name: 'peptides_in:0',
   data_type: TYPE_FP32,
   dims: [60,20]
 }
]
instance_group [
    {
      count: 1
      kind: KIND_CPU
    }
]
