name: "ms2pip_preprocess"
max_batch_size: 5000
backend: "python"
input[
 {
   name: 'proforma',
   data_type: TYPE_STRING,
   dims: [-1]
 },
 {
   name: 'charge_in',
   data_type: TYPE_INT32,
   dims: [-1]
 }
]
output [
 {
   name: 'xgboost_input',
   data_type: TYPE_FP32,
   dims: [139]
 }
]
instance_group [
    {
      count: 1
      kind: KIND_CPU
    }
]
