max_batch_size: 7000
platform: "ensemble"
input [
  {
   name: 'peptide_sequences',
   data_type: TYPE_STRING,
   dims: [-1]
  },
  {
    name: 'precursor_charge',
    data_type: TYPE_INT32,
    dims: [1],
  }
]
output [
  {
   name: 'intensities',
   data_type: TYPE_FP32,
   dims: [174]
  },
 {
   name: 'mz',
   data_type: TYPE_FP32,
   dims: [174]
 }
]

ensemble_scheduling {
  step [
     {
      model_name: "Prosit_Preprocess_charge"
      model_version: 1
      input_map {
        key: "precursor_charge"
        value: "precursor_charge"
      },
      output_map {
        key: "precursor_charge_in:0"
        value: "precursor_charge_in_preprocessed:0"
      }
    },
    {
      model_name: "Prosit_Helper_NCE35"
      model_version: 1
      input_map {
        key: "precursor_charge"
        value: "precursor_charge"
      },
      output_map {
        key: "collision_energies"
        value: "collision_energies"
      }
    },
    {
      model_name: "Prosit_Preprocess_peptide"
      model_version: 1
      input_map {
        key: "peptide_sequences"
        value: "peptide_sequences"
      },
      output_map {
        key: "peptides_in:0"
        value: "peptides_in:0"
      }
    },
    {
      model_name: "Prosit_2020_intensity_CID_core"
      model_version: 1
      input_map {
        key: "peptides_in:0"
        value: "peptides_in:0"
      },
      input_map {
        key: "collision_energy_in:0"
        value: "collision_energies"
      },
      input_map {
        key: "precursor_charge_in:0"
        value: "precursor_charge_in_preprocessed:0"
      }
      output_map {
        key: "out/Reshape:0"
        value: "out/Reshape:0"
      }
    },
    {
      model_name: "Prosit_2019_intensity_postprocess"
      model_version: 1
      input_map {
        key: "peptides_in:0"
        value: "peptide_sequences"
      },
      input_map{
        key: "precursor_charge_in:0"
        value: "precursor_charge_in_preprocessed:0"
      }
      input_map{
        key: "peaks_in:0",
        value: "out/Reshape:0"
      }
      output_map {
        key: "intensities"
        value: "intensities"
      }
      output_map {
        key: "mz"
        value: "mz"
      }
    }
  ]
}
