name: "AlphaPept_Preprocess_ce"
max_batch_size: 7000
backend: "python"
input[
 {
   name: 'ce_raw',
   data_type: TYPE_INT32,
   dims: [1]
 }
]
output [
 {
   name: 'ce_norm',
   data_type: TYPE_FP32,
   dims: [1]
 }
]
