name: "ms2pip_postprocess_merge_and_norm"
backend: "python"
max_batch_size: 500
input[
 {
   name: 'raw_intensities_y',
   data_type: TYPE_FP32,
   dims: [ 29 ],
 },
 {
   name: 'raw_intensities_b',
   data_type: TYPE_FP32,
   dims: [ 29 ],
 }
]
output [
 {
   name: 'intensities',
   data_type: TYPE_FP32,
   dims: [ 58 ]
 }
]
