name: "ms2pip_postprocess_single_model"
max_batch_size: 10
backend: "python"
input[
 {
   name: 'xgboost_output__0',
   data_type: TYPE_FP32,
   dims: [1]
 }
]
output [
 {
   name: 'ion_series_prediction',
   data_type: TYPE_FP32,
   dims: [29]
 }
]
instance_group [
    {
      count: 1
      kind: KIND_CPU
    }
]
