max_batch_size: 1000

input [
   {
   name: 'peptide_sequences',
   data_type: TYPE_STRING,
   dims: [-1]
  }
]

output [
 {
   name: 'sequence_encoded',
   data_type: TYPE_FP32,
   dims: [23,40]
 }
]
