name: "ensemble_model"
platform: "ensemble"
max_batch-size: 1
input [
  {
    name: "label"
    data_type: BYTES
    dims: [1]
  }
]
output [
  {
    name: "intensities"
    data_type: TYPE_FP32
    dims: [7918]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: uspreprocess
      model_version: -1
      input_map {
        key: "label"
        value: "input_tensor"
      }
    },
    {
      model_name: "unispec23"
      model_version: -1
      input_map {
        key: "input_tensor"
        value: "input_tensor___"
      }
      output_map {
        key: "intensities1"
        value: "intensities2"
      }
    }
  ]
}
