name: "ms2pip_2021_HCD"
max_batch_size: 500
platform: "ensemble"
input [
  {
   name: 'peptide_sequences',
   data_type: TYPE_STRING,
   dims: [-1]
  },
  {
   name: 'precursor_charge',
   data_type: TYPE_INT16,
   dims: [1]
  }
]
output [
  {
   name: 'intensities',
   data_type: TYPE_FP32,
   dims: [58]
  },
  {
   name: 'mz',
   data_type: TYPE_FP32,
   dims: [58]
  }
]

ensemble_scheduling {
  step [
     {
      model_name: "ms2pip_preprocess"
      model_version: 1
      input_map {
        key: "proforma" 
        value: "peptide_sequences"
      },
      input_map {
        key: "charge_in" 
        value: "precursor_charge"
      },
      output_map {
        key: "xgboost_input"
        value: "xgboost_input"
      }
    },
     {
      model_name: "model_20210416_HCD2021_B"
      model_version: 1
      input_map {
        key: "input__0" 
        value: "xgboost_input"
      },
      output_map {
        key: "output__0"
        value: "model_20210416_HCD2021_B_output"
      }
    },
     {
      model_name: "model_20210416_HCD2021_Y"
      model_version: 1
      input_map {
        key: "input__0" 
        value: "xgboost_input"
      },
      output_map {
        key: "output__0"
        value: "model_20210416_HCD2021_Y_output"
      }
    },
     {
      model_name: "ms2pip_postprocess_single_model"
      model_version: 1
      input_map {
        key: "raw_intensities" 
        value: "model_20210416_HCD2021_B_output"
      },
      output_map {
        key: "norm_intensities"
        value: "norm_intensities_b"
      }
    },
     {
      model_name: "ms2pip_postprocess_single_model"
      model_version: 1
      input_map {
        key: "raw_intensities" 
        value: "model_20210416_HCD2021_Y_output"
      },
      output_map {
        key: "norm_intensities"
        value: "norm_intensities_y"
      }
    },
     {
      model_name: "ms2pip_postprocess_merge_and_norm"
      model_version: 1
      input_map {
        key: "raw_intensities_y" 
        value: "norm_intensities_y"
      },
      input_map {
        key: "raw_intensities_b" 
        value: "norm_intensities_b"
      },
      output_map {
        key: "intensities"
        value: "intensities"
      }
    },
     {
      model_name: "ms2pip_fragmentmz_wrapper"
      model_version: 1
      input_map {
        key: "peptides_in:0" 
        value: "peptide_sequences"
      }
      output_map {
        key: "mz"
        value: "mz"
      }
    }
  ]
}
