name: "3dmolms_torch"
backend: "pytorch"
max_batch_size : 256
input [
  {
    name: "x"
    data_type: TYPE_FP32
    dims: [21, 300]
  },
  {
    name: "env"
    data_type: TYPE_FP32
    dims: [6]
  },
  {
    name: "idx_base"
    data_type: TYPE_INT32
    dims: [-1, 1, 1]
  }
]
output [
  {
    name: "3dmolms_out"
    data_type: TYPE_FP32
    dims: [7500]
  }
]
instance_group [{ kind: KIND_AUTO }]
