platform: "pytorch_libtorch"
max_batch_size: 1000
input[
  {
   name: 'aa_indices__0',
   data_type: TYPE_INT64,
   dims: [-1]
  },
  {
   name: 'mod_x__1',
   data_type: TYPE_FP32,
   dims: [-1,109],
  },
  {
   name: 'charges__2',
   data_type: TYPE_FP32,
   dims: [1],
  },
  {
   name: 'NCEs__3',
   data_type: TYPE_FP32,
   dims: [1],
  },
  {
   name: 'instrument_indices__4',
   data_type: TYPE_INT64,
   dims: [1],
   reshape: { shape: [ ] }
  }
]
output [
 {
   name: 'output__0',
   data_type: TYPE_FP32,
   dims: [-1,8],
 }
]
model_repository_agents
{
  agents [
    {
      name: "checksum",
      parameters
      {
        key: "MD5:./1/model.pt",
        value: "4cd4f26203898264db9e90f1fab309ce"
      }
    }
  ]
}
