max_batch_size: 1000

input[
  {
   name: 'peptides_in_1:0',
   data_type: TYPE_STRING,
   dims: [-1]
  },
  {
   name: 'peptides_in_2:0',
   data_type: TYPE_STRING,
   dims: [-1]
  },
  {
	name: 'precursor_charges_in:0',
	data_type: TYPE_FP32,
	dims: [6],
	},
  {
   name: 'peaks_in:0',
   data_type: TYPE_FP32,
   dims: [348]
  }
]
output [
 {
   name: 'intensities',
   data_type: TYPE_FP32,
   dims: [348]
 },
 {
   name: 'mz',
   data_type: TYPE_FP32,
   dims: [348]
 }
]