name: "multifrag25"
backend: "pytorch"
max_batch_size: 1000
input [
  {
   name: 'intseq',
   data_type: TYPE_INT32,
   dims: [ 30 ]
  },
  {
   name: 'charge',
   data_type: TYPE_INT32,
   dims: [ 1 ],
   reshape: { shape: [ ] }
  },
  {
   name: 'energy',
   data_type: TYPE_FP32,
   dims: [ 1 ],
   reshape: { shape: [ ] }
  },
  {
   name: 'method',
   data_type: TYPE_INT32,
   dims: [ 1 ],
   reshape: { shape: [ ] }
  }
]
output [
  {
   name: 'intensities',
   data_type: TYPE_FP32,
   dims: [ 815 ]
  }
]
