max_batch_size: 1000

input[
  {
   name: 'spectrum',
   data_type: TYPE_FP32,
   dims: [20000]
  },
  {
   name: 'precursor_mass_with_oxM',
   data_type: TYPE_FP32,
   dims: [1]
  }
]
output [
 {
   name: 'mzs',
   data_type: TYPE_FP32,
   dims: [-1]
 },
 {
   name: 'intensities',
   data_type: TYPE_FP32,
   dims: [-1]
 }
]
