name: "ms2pip_ensemble"
max_batch_size: 500
platform: "ensemble"
input [
  {
   name: 'proforma_ensemble',
   data_type: TYPE_STRING,
   dims: [-1]
  }
]
output [
  {
   name: 'model_20210416_HCD2021_B_output',
   data_type: TYPE_FP32,
   dims: [ 1]
  }
]

ensemble_scheduling {
  step [
     {
      model_name: "ms2pip_preprocess"
      model_version: 1
      input_map {
        key: "proforma" 
        value: "proforma_ensemble"
      },
      output_map {
        key: "xgboost_input"
        value: "xgboost_input"
      }
    },
     {
      model_name: "model_20210416_HCD2021_B"
      model_version: 1
      input_map {
        key: "input__0" 
        value: "xgboost_input"
      },
      output_map {
        key: "output__0"
        value: "model_20210416_HCD2021_B_output"
      }
    }
  ]
}
