max_batch_size: 7000

input[
  {
   name: 'peptides_in:0',
   data_type: TYPE_STRING,
   dims: [-1]
  },
  {
	  name: 'precursor_charge_in:0',
	  data_type: TYPE_FP32,
	  dims: [6],
	},
  {
   name: 'peaks_in:0',
   data_type: TYPE_FP32,
   dims: [174]
  }
]
output [
 {
   name: 'out/Reshape:1',
   data_type: TYPE_FP32,
   dims: [174]
 },
 {
   name: 'out/Reshape:2',
   data_type: TYPE_FP32,
   dims: [174]
 }
]
