max_batch_size: 5000
input[
 {
   name: 'stripped_peptide',
   data_type: TYPE_STRING,
   dims: [1]
 }
]
output [
 {
   name: 'peptide_length',
   data_type: TYPE_FP32,
   dims: [1]
 }
]
instance_group [
    {
      count: 1
      kind: KIND_CPU
    }
]
