max_batch_size: 1000
platform: "ensemble"
input [
  {
   name: 'peptide_sequences',
   data_type: TYPE_STRING,
   dims: [-1]
  },
  {
    name: 'precursor_charges',
    data_type: TYPE_INT32,
    dims: [1],
  }
]
output [
  {
   name: 'ccs',
   data_type: TYPE_FP32,
   dims: [1]
  }
]

ensemble_scheduling {
  step [
     {
      model_name: "AlphaPept_Preprocess_ProForma"
      model_version: 1
      input_map {
        key: "peptide_sequences"
        value: "peptide_sequences"
      },
      output_map {
        key: "encoded_seq:0"
        value: "encoded_seq"
      },
      output_map {
        key: "encoded_mod_feature:0"
        value: "encoded_mod_features"
      }
    },
    {
      model_name: "AlphaPept_Preprocess_charge"
      model_version: 1
      input_map {
        key: "charge_raw"
        value: "precursor_charges"
      },
      output_map {
        key: "charge_norm"
        value: "charge_norm"
      }
    },
    {
      model_name: "AlphaPept_ccs_generic_core"
      model_version: 1
      input_map {
        key: "aa_indices__0"
        value: "encoded_seq"
      },
      input_map {
        key: "mod_x__1"
        value: "encoded_mod_features"
      },
      input_map {
        key: "charges__2"
        value: "charge_norm"
      }
      output_map {
        key: "output__0"
        value: "ccs_raw"
      }
    },
    {
      model_name: "AlphaPept_ccs_generic_postprocess"
      model_version: 1
      input_map {
        key: "ccs_raw"
        value: "ccs_raw"
      },
      output_map {
        key: "ccs"
        value: "ccs"
      }
    }
  ]
}
