max_batch_size: 1000

input [
  {
   name: 'intensities',
   data_type: TYPE_FP32,
   dims: [1900]
  },
  {
   name: 'annotations',
   data_type: TYPE_STRING,
   dims: [1900]
  },
  {
   name: 'mz',
   data_type: TYPE_FP32,
   dims: [1900]
  }
]

output [
  {
   name: 'intensities_filtered',
   data_type: TYPE_FP32,
   dims: [1900]
  },
  {
   name: 'annotations_filtered',
   data_type: TYPE_STRING,
   dims: [1900]
  },
  {
   name: 'mz_filtered',
   data_type: TYPE_FP32,
   dims: [1900]
  }
]